apiVersion: v1
kind: Service
metadata:
  name: kubernetes-project-service
spec:
  selector:
    app: kubernetes-project
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000  # Specify a static NodePort number
  type: LoadBalancer  # Change the type to NodePort
