apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-project
  template:
    metadata:
      labels:
        app: kubernetes-project
    spec:
      containers:
      - name: kubernetes-project-container
        image: dangyan03/kubernetes:microservice
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: postgres-container  # Replace with the actual service name of PostgreSQL

